

apiVersion: backstage.io/v1alpha1
kind: Component

metadata: 
  name: backstage-test1
  annotations:
    jira.com/project-key: KAN123
    # jira.com/filter-ids: 1,2
 
  # Example for optional annotations
  # annotations:
  #   github.com/project-slug: backstage/backstage
  #   backstage.io/techdocs-ref: dir:.
spec:
  type: website
  owner: john@example.com
  lifecycle: experimental
